# Generated by Django 2.0.13 on 2020-02-02 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='defaultModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('defaultmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Login.defaultModel')),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('postcode', models.IntegerField()),
            ],
            options={
                'ordering': ['country'],
            },
            bases=('Login.defaultmodel',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('defaultmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Login.defaultModel')),
                ('salutation', models.CharField(choices=[('Mr.', 'Mister'), ('Ms.', 'Miss'), ('Mrs.', 'Mistress')], default=None, max_length=4)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('birthdate', models.CharField(max_length=15)),
            ],
            bases=('Login.defaultmodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('defaultmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Login.defaultModel')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            bases=('Login.defaultmodel',),
        ),
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Person'),
        ),
    ]
