# Generated by Django 2.0.13 on 2020-02-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('defaultmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Login.defaultModel')),
                ('profileImage', models.ImageField(upload_to='')),
                ('frequentTraveller', models.BooleanField(default=False)),
                ('hasBlog', models.URLField()),
                ('occupation', models.CharField(max_length=30, null=True)),
                ('motivation', models.TextField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.Person')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.User')),
            ],
            bases=('Login.defaultmodel',),
        ),
    ]
