# Generated by Django 2.0.13 on 2020-02-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hasBlog',
            field=models.URLField(null=True),
        ),
    ]
